#!/usr/bin/env python3
#
# imud — IMU daemon
# Copyright (c) 2026 Richard Simpson
# SPDX-License-Identifier: MIT
#
"""
man-postprocess.py — make help2man's output reproducible and consistent.

`make docs-man` regenerates the man1/man8 pages and CI asserts the result
matches what is committed.  That gate only works if two runs of help2man
produce identical bytes, and by default they do not:

  1. help2man stamps its OWN version into the file —
     `.\\" ... generated by help2man 1.49.3.` — so a CI runner whose help2man
     differs from the maintainer's turns the diff permanently red.

  2. It formats the .TH date as "%B %Y" ("August 2026").  That is not this
     project's format (all pages use ISO 2026-08-05), it breaks
     bump-version.sh's ISO regex, and it changes by itself every month, so the
     gate would fail on the first of each month with nothing having changed.

  3. mandoc -Wstyle objects to trailing whitespace, which help2man emits on
     otherwise-blank continuation lines.

SOURCE_DATE_EPOCH fixes only (2).  This fixes all three, and in doing so makes
the output independent of help2man's version, the locale and the clock —
which is what lets the pages be committed and diffed at all.

The version and date both come from include/version.h, so a release bump moves
them and nothing else does.

Usage: man-postprocess.py PAGE...
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from checklib import must_read                                  # noqa: E402

HDR = "include/version.h"

# .TH NAME SECTION "date" "source" "manual"
TH = re.compile(r'^\.TH\s+(\S+)\s+"?(\w+)"?\s+"[^"]*"\s+"[^"]*"\s+"([^"]*)"',
                re.M)


def release():
    """(version, date) from include/version.h — the one place either lives."""
    src = must_read(HDR, "the canonical version")
    v = re.search(r'#define\s+IMUD_VERSION_STR\s+"([^"]+)"', src)
    d = re.search(r'#define\s+IMUD_RELEASE_DATE\s+"([^"]+)"', src)
    if not v or not d:
        sys.exit(f"{HDR}: need both IMUD_VERSION_STR and IMUD_RELEASE_DATE")
    return v.group(1), d.group(1)


def process(path, version, date):
    with open(path, encoding="utf-8") as f:
        text = f.read()

    m = TH.search(text)
    if not m:
        sys.exit(f"{path}: no parsable .TH line — did help2man fail?")
    name, section, manual = m.group(1), m.group(2), m.group(3)

    # One canonical .TH, matching the hand-written pages byte for byte in
    # shape: ISO date, "imud <version>" as the source, section manual last.
    th = f'.TH {name} {section} "{date}" "imud {version}" "{manual}"'
    text = TH.sub(lambda _: th, text, count=1)

    # Replace help2man's self-identifying banner with one that does not carry
    # a tool version, and that tells a reader where to make the change.
    page = os.path.basename(path)
    text = re.sub(r'^\.\\" DO NOT MODIFY THIS FILE![^\n]*\n',
                  f'.\\" GENERATED from `{page[:-2]} --help` and '
                  f'man/h2m/{page}.h2m — do not edit.\n'
                  f'.\\" Regenerate with `make docs-man`.\n',
                  text, count=1, flags=re.M)

    text = re.sub(r"[ \t]+$", "", text, flags=re.M)     # mandoc -Wstyle
    if not text.endswith("\n"):
        text += "\n"

    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    pages = sys.argv[1:]
    if not pages:
        sys.exit("usage: man-postprocess.py PAGE...")
    version, date = release()
    for p in pages:
        process(p, version, date)
    print(f"man-postprocess: {len(pages)} page(s) stamped "
          f"imud {version} ({date})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
